# Generated by Django 5.0.1 on 2024-01-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('can_create_account', models.BooleanField(default=False)),
                ('authenticated', models.BooleanField(default=False)),
                ('can_create_chat', models.BooleanField(default=False)),
                ('friend_search', models.CharField(max_length=20)),
                ('message_to_send', models.CharField(max_length=500)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('time_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
